import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getFirestore, collection, getDocs, query, orderBy } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';
const user=JSON.parse(sessionStorage.getItem('fllUser')||'null'); if(!user||user.role!=='admin') location.href='index.html';
document.getElementById('logout').onclick=()=>{sessionStorage.clear();location.href='index.html'};
const db=getFirestore(initializeApp(firebaseConfig)); let rows=[];
async function load(){const status=document.getElementById('status'); status.textContent='Carregando...'; try{const snap=await getDocs(query(collection(db,'avaliacoes_fll'),orderBy('createdAtLocal','desc'))); rows=snap.docs.map(d=>({id:d.id,...d.data()})); render(); status.textContent=`${rows.length} avaliação(ões) encontrada(s).`;}catch(e){console.error(e); status.textContent='Erro ao carregar. Confira configuração e regras do Firestore.'}}
function render(){const team=document.getElementById('filterTeam').value.toLowerCase(); const type=document.getElementById('filterType').value; const tb=document.querySelector('#table tbody'); tb.innerHTML=''; rows.filter(r=>(!type||r.type===type)&&(!team||`${r.teamNumber} ${r.teamName}`.toLowerCase().includes(team))).forEach(r=>{tb.insertAdjacentHTML('beforeend',`<tr><td>${r.createdAtLocal||''}</td><td>${r.typeTitle||r.type}</td><td><b>${r.teamNumber||''}</b> - ${r.teamName||''}</td><td>${r.judge||''}</td><td>${r.room||''}</td><td>${r.total||0}</td><td>${r.avg||''}</td><td>${r.generalNotes||''}</td></tr>`)});}
function csv(){let out='Data;Tipo;Equipe Numero;Equipe Nome;Juiz;Sala;Total;Media;Observacoes\n'; rows.forEach(r=>{out += [r.createdAtLocal,r.typeTitle,r.teamNumber,r.teamName,r.judge,r.room,r.total,r.avg,r.generalNotes].map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')+'\n'}); const blob=new Blob(['\ufeff'+out],{type:'text/csv;charset=utf-8'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='avaliacoes-fll.csv'; a.click();}
document.getElementById('load').onclick=load; document.getElementById('exportCsv').onclick=csv; document.getElementById('filterTeam').oninput=render; document.getElementById('filterType').onchange=render; load();
